language: python
python:
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - postgresql  
  
before_install:
  - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
  - unzip sonar-runner-dist-2.4.zip
before_script:
  - psql -c 'create database incaper;' -U postgres
  #- psql -U postgres -d incaper -a -f dados_teste/sqls/backup-20160105-2.sql

branches:
  only:
    - master
    - desenvolvimwento
install:
  - pip install -r requirements.txt
script: 
  - python sipac/manage.py test
  - nosetests

after_script:
 - ./sonar-runner-2.4/bin/sonar-runner
notifications:
  slack: leds:ecBlZedCK8tpP1X5uygKMS8q
