version: '2'
services:
    db:
        build: dockerfiles/postgres
        ports:
            - 5432
        environment:
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_USER=postgres
            - POSTGRES_DB=Incaper
        volumes:
            - ./dados_teste/sqls/ModeloFisico/Modelo_Fisico_Sipac.sql:/docker-entrypoint-initdb.d/V1_1__Modelo_Fisico_Sipac.sql
            - ./dados_teste/sqls/Consultas/funcoes.sql:/docker-entrypoint-initdb.d/V1_2__funcoes.sql
    pentaho-biserver:
        image: wmarinho/pentaho-biserver:6.1
        ports:
            - "8080"
        links:
            - db
    pentaho-pdi:
        container_name: pdi
        build: dockerfiles/pentaho-pdi
        ports:
            - "8181"
        links:
            - db
            - pentaho-biserver
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
            - ./transformacoes.sh:/opt/pentaho/data-integration/transformacoes.sh
            - ./dados_teste:/opt/pentaho/data-integration/dados_teste
            - ./dados_teste:/home/cristian/Documentos/LEDS/Projetos/Incaper/sipac-backend/dados_teste
            - ./dados_teste:/home/cristian/Documentos/LEDS/Projetos/Incaper/Testes Produção/files
            - ./dados_teste/csv/Produtos.csv:/home/cristian/Documentos/LEDS/Projetos/Incaper/Pentaho/Pentaho 5.4/Dados/[DICIONARIO DE CAMPOS] Produtos.csv
            - ./transformacoes:/opt/pentaho/data-integration/samples/transformations/Sipac
            - ./jobs:/opt/pentaho/data-integration/samples/jobs/Sipac
            - $HOME/.kettle:/home/pentaho/.kettle
        environment:
            - XAUTH=/tmp/.docker.xauth
            - XAUTHORITY=/tmp/.docker.xauth
            - DISPLAY=$DISPLAY
