version: '2'
services:
    db:
        build: dockerfiles/postgres
        ports:
            - 5432
        environment:
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_USER=postgres
            - POSTGRES_DB=Incaper
    migrations:
        build: dockerfiles/migrations
        links:
            - db
            - web
        depends_on:
            - web
        environment:
            - DATABASE_NAME=Incaper
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=admin123
            - DATABASE_PORT=5432
            - DATABASE_ENCODING=utf8
            - DATABASE_DRIVER=postgresql
            - MIGRATIONS_PATH=/home/flyway/sql
    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "8000"
        depends_on:
            - db
        links:
            - db
        environment:
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
    pentaho-biserver:
        image: wmarinho/pentaho-biserver:6.1
        ports:
            - "8080"
        links:
            - db
    pentaho-pdi:
        container_name: pdi
        build: dockerfiles/pentaho-pdi
        ports:
            - "8181"
        links:
            - db
            - pentaho-biserver
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
            - ./transformacoes.sh:/opt/pentaho/data-integration/transformacoes.sh
            - ./dados_teste:/opt/pentaho/data-integration/dados_teste
            - ./dados_teste:/home/cristian/Documentos/LEDS/Projetos/Incaper/sipac-backend/dados_teste
            - ./dados_teste:/home/cristian/Documentos/LEDS/Projetos/Incaper/Testes Produção/files
            - ./transformacoes:/opt/pentaho/data-integration/samples/transformations/Sipac
            - ./jobs:/opt/pentaho/data-integration/samples/jobs/Sipac
            - $HOME/.kettle:/home/pentaho/.kettle
        environment:
            - XAUTH=/tmp/.docker.xauth
            - XAUTHORITY=/tmp/.docker.xauth
            - DISPLAY=$DISPLAY
