# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20160104_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('preco', models.FloatField()),
                ('mesoregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MesoRegiao')),
                ('microregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MicroRegiao')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio')),
            ],
            options={
                'ordering': ['ano', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='producao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.Produto'),
        ),
    ]
