# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('area_plantada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_em_producao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_colhida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_em_formacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irrigado', models.BooleanField(default=False)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio')),
            ],
            options={
                'ordering': ['ano'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='producao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.Produto'),
        ),
    ]
