# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_data'),
        ('agricultura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'ordering': ['data']},
        ),
        migrations.RemoveField(
            model_name='producao',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='mes',
        ),
        migrations.AddField(
            model_name='producao',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Data'),
            preserve_default=False,
        ),
    ]
