# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0002_auto_20160215_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subgrupo', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='producao',
            old_name='area_em_producao',
            new_name='producao',
        ),
        migrations.AddField(
            model_name='producao',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
