# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0002_auto_20160110_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'ordering': ['ano']},
        ),
        migrations.RemoveField(
            model_name='producao',
            name='data',
        ),
        migrations.AddField(
            model_name='producao',
            name='ano',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producao',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
