# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0003_auto_20160223_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgrupo',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agricultura.Grupo'),
            preserve_default=False,
        ),
    ]
