# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0004_subgrupo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subgrupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agricultura.Subgrupo'),
            preserve_default=False,
        ),
    ]
