# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0005_produto_subgrupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='subgrupo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='grupo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='agricultura.Grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agricultura.Grupo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subgrupo',
        ),
    ]
