# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0006_auto_20160224_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='agricultura.Grupo'),
        ),
    ]
