# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesoregiao',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Estado'),
            preserve_default=False,
        ),
    ]
