# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mesoregiao_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='mesoregiao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='microregiao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Estado'),
            preserve_default=False,
        ),
    ]
