# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0003_auto_20160118_0138'),
        ('core', '0004_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
